/*
 Navicat Premium Data Transfer

 Source Server         : localdb
 Source Server Type    : PostgreSQL
 Source Server Version : 130003
 Source Host           : localhost:5432
 Source Catalog        : tourappapi
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 130003
 File Encoding         : 65001

 Date: 29/07/2021 11:39:54
*/


-- ----------------------------
-- Sequence structure for agentrequests_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."agentrequests_id_seq";
CREATE SEQUENCE "public"."agentrequests_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for agents_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."agents_id_seq";
CREATE SEQUENCE "public"."agents_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for client_info_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."client_info_id_seq";
CREATE SEQUENCE "public"."client_info_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for confirmation_tokens_token_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."confirmation_tokens_token_id_seq";
CREATE SEQUENCE "public"."confirmation_tokens_token_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for offers_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."offers_id_seq";
CREATE SEQUENCE "public"."offers_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for requests_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "public"."requests_id_seq";
CREATE SEQUENCE "public"."requests_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for agentrequests
-- ----------------------------
DROP TABLE IF EXISTS "public"."agentrequests";
CREATE TABLE "public"."agentrequests" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "status" int4,
  "agent_id" int4,
  "request_id" int4,
  "clientinfo_id" int4
)
;

-- ----------------------------
-- Table structure for agents
-- ----------------------------
DROP TABLE IF EXISTS "public"."agents";
CREATE TABLE "public"."agents" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "agent_name" varchar(255) COLLATE "pg_catalog"."default",
  "company_name" varchar(255) COLLATE "pg_catalog"."default",
  "email" varchar(255) COLLATE "pg_catalog"."default",
  "is_active" bool,
  "username" varchar(255) COLLATE "pg_catalog"."default",
  "voen" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for client_info
-- ----------------------------
DROP TABLE IF EXISTS "public"."client_info";
CREATE TABLE "public"."client_info" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "contact_information" varchar(255) COLLATE "pg_catalog"."default",
  "first_name" varchar(255) COLLATE "pg_catalog"."default",
  "last_name" varchar(255) COLLATE "pg_catalog"."default",
  "username" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for confirmation_tokens
-- ----------------------------
DROP TABLE IF EXISTS "public"."confirmation_tokens";
CREATE TABLE "public"."confirmation_tokens" (
  "token_id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
),
  "confirmation_token" varchar(255) COLLATE "pg_catalog"."default",
  "created_date" timestamp(6),
  "agent_id" int4 NOT NULL
)
;

-- ----------------------------
-- Table structure for offers
-- ----------------------------
DROP TABLE IF EXISTS "public"."offers";
CREATE TABLE "public"."offers" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "image_path" varchar(255) COLLATE "pg_catalog"."default",
  "agent_id" int4,
  "agentrequest_id" int4,
  "is_accepted" bool
)
;

-- ----------------------------
-- Table structure for requests
-- ----------------------------
DROP TABLE IF EXISTS "public"."requests";
CREATE TABLE "public"."requests" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "deadline" timestamp(6),
  "is_active" bool DEFAULT true,
  "questions_json" varchar(255) COLLATE "pg_catalog"."default",
  "status" int4,
  "uuid" varchar(255) COLLATE "pg_catalog"."default",
  "answers_json" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."agentrequests_id_seq"
OWNED BY "public"."agentrequests"."id";
SELECT setval('"public"."agentrequests_id_seq"', 67, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."agents_id_seq"
OWNED BY "public"."agents"."id";
SELECT setval('"public"."agents_id_seq"', 7, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."client_info_id_seq"
OWNED BY "public"."client_info"."id";
SELECT setval('"public"."client_info_id_seq"', 19897, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."confirmation_tokens_token_id_seq"
OWNED BY "public"."confirmation_tokens"."token_id";
SELECT setval('"public"."confirmation_tokens_token_id_seq"', 5, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."offers_id_seq"
OWNED BY "public"."offers"."id";
SELECT setval('"public"."offers_id_seq"', 10, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "public"."requests_id_seq"
OWNED BY "public"."requests"."id";
SELECT setval('"public"."requests_id_seq"', 40, true);

-- ----------------------------
-- Primary Key structure for table agentrequests
-- ----------------------------
ALTER TABLE "public"."agentrequests" ADD CONSTRAINT "agentrequests_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table agents
-- ----------------------------
ALTER TABLE "public"."agents" ADD CONSTRAINT "agents_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table client_info
-- ----------------------------
ALTER TABLE "public"."client_info" ADD CONSTRAINT "client_info_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table confirmation_tokens
-- ----------------------------
ALTER TABLE "public"."confirmation_tokens" ADD CONSTRAINT "confirmation_tokens_pkey" PRIMARY KEY ("token_id");

-- ----------------------------
-- Primary Key structure for table offers
-- ----------------------------
ALTER TABLE "public"."offers" ADD CONSTRAINT "offers_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Primary Key structure for table requests
-- ----------------------------
ALTER TABLE "public"."requests" ADD CONSTRAINT "requests_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table agentrequests
-- ----------------------------
ALTER TABLE "public"."agentrequests" ADD CONSTRAINT "fk1q2g00pbc9yj0h9rq2x8pxxa9" FOREIGN KEY ("agent_id") REFERENCES "public"."agents" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."agentrequests" ADD CONSTRAINT "fkd7sketgit7s8ox51ur8ur14ec" FOREIGN KEY ("request_id") REFERENCES "public"."requests" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."agentrequests" ADD CONSTRAINT "fkliv84xlufdc7xkhlxb60ma7k0" FOREIGN KEY ("clientinfo_id") REFERENCES "public"."client_info" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table confirmation_tokens
-- ----------------------------
ALTER TABLE "public"."confirmation_tokens" ADD CONSTRAINT "fklqt9gjakq98c3ijbrlvymg08l" FOREIGN KEY ("agent_id") REFERENCES "public"."agents" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table offers
-- ----------------------------
ALTER TABLE "public"."offers" ADD CONSTRAINT "fko14ad1rfe0nwurx2rls779jnk" FOREIGN KEY ("agent_id") REFERENCES "public"."agents" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "public"."offers" ADD CONSTRAINT "fkrvq112oxsgm6ad1n3568qok6f" FOREIGN KEY ("agentrequest_id") REFERENCES "public"."agentrequests" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION;
